[package]
name = "gjk-algorithm"
version = "0.1.0"
edition = "2021"
default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
nannou = { workspace = true }
nannou_egui = { workspace = true }
